apiVersion: apps/v1
kind: Deployment
metadata:
  name: salkim-redis
  namespace: salkim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salkim-redis
  template:
    metadata:
      labels:
        app: salkim-redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: salkim-redis
  namespace: salkim
spec:
  selector:
    app: salkim-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
